spring:
  profiles:
    active: dev
    default: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/list-aplic-api
    username: postgre-user-test
    password: postgre-passwd-test

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    show-sql: true
    generate-ddl: true
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      temp:
        use_jdbc_metadata_defaults: false

management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: "*"
  server:
    port: 8089
    context-path: /

server:
  port: 8088
  servlet:
    context-path: /api

---
spring:
  profiles:
    active: prod

  datasource:
    url: jdbc:postgresql://ec2-54-197-241-96.compute-1.amazonaws.com:5432/d79arfcgk17kag
    username: ynqmreiuohquyn
    password: 11c9c887d86b35d5e4cc4bf26fd7802b1f68a17dddd6c089aeb9e6a3c2076d4d

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false

management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: "*"
  server:
    port: 8080
    context-path: /

server:
  port: 80
  servlet:
    context-path: /api